on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: pytest
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: windows-latest, py: "3.7" }
                    - { os: macOS-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.7" }
                    - { os: ubuntu-latest, py: "3.9" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.8.0
              with:
                access_token: ${{ github.token }}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install .[ci]
            - name: Install MPI
              if: "contains(matrix.config.os, 'ubuntu')"
              run: |
                  sudo apt-get update
                  sudo apt-get install -y mpi-default-dev
                  pip install mpi4py
            - name: run pytest
              run: |
                  pytest
            - name: build docs
              run: |
                  python -m pip install .[docs]
                  make -C docs html
